// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactRecords.proto

package com.example.database_test.gmsreadout;

public final class ContactRecordsProtos {
  private ContactRecordsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScanRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ScanRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 timestamp = 1;</code>
     */
    int getTimestamp();

    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     */
    boolean hasRssiMultipleValues();
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     */
    com.google.protobuf.ByteString getRssiMultipleValues();

    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated boolean hasRssi();
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated int getRssi();

    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getAemMultipleValuesList();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    int getAemMultipleValuesCount();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    com.google.protobuf.ByteString getAemMultipleValues(int index);

    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     */
    @java.lang.Deprecated boolean hasAem();
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     */
    @java.lang.Deprecated com.google.protobuf.ByteString getAem();

    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     */
    boolean hasPreviousScanTimestamp();
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     */
    int getPreviousScanTimestamp();

    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     */
    boolean hasLatitude();
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     */
    double getLatitude();

    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     */
    boolean hasLongitude();
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     */
    double getLongitude();

    /**
     * <code>optional uint32 activity = 9;</code>
     */
    boolean hasActivity();
    /**
     * <code>optional uint32 activity = 9;</code>
     */
    int getActivity();

    /**
     * <code>optional string label = 10;</code>
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 10;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 10;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>optional double prob = 11;</code>
     */
    boolean hasProb();
    /**
     * <code>optional double prob = 11;</code>
     */
    double getProb();

    /**
     * <code>optional string vectors = 12;</code>
     */
    boolean hasVectors();
    /**
     * <code>optional string vectors = 12;</code>
     */
    java.lang.String getVectors();
    /**
     * <code>optional string vectors = 12;</code>
     */
    com.google.protobuf.ByteString
        getVectorsBytes();
  }
  /**
   * Protobuf type {@code gmsreadout.ScanRecord}
   */
  public  static final class ScanRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ScanRecord)
      ScanRecordOrBuilder {
    // Use ScanRecord.newBuilder() to construct.
    private ScanRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanRecord() {
      timestamp_ = 0;
      rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
      rssi_ = 0;
      aemMultipleValues_ = java.util.Collections.emptyList();
      aem_ = com.google.protobuf.ByteString.EMPTY;
      previousScanTimestamp_ = 0;
      latitude_ = 0D;
      longitude_ = 0D;
      activity_ = 0;
      label_ = "";
      prob_ = 0D;
      vectors_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScanRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rssiMultipleValues_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rssi_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              aem_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              previousScanTimestamp_ = input.readUInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                aemMultipleValues_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              aemMultipleValues_.add(input.readBytes());
              break;
            }
            case 57: {
              bitField0_ |= 0x00000020;
              latitude_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000040;
              longitude_ = input.readDouble();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              activity_ = input.readUInt32();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              label_ = bs;
              break;
            }
            case 89: {
              bitField0_ |= 0x00000200;
              prob_ = input.readDouble();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              vectors_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          aemMultipleValues_ = java.util.Collections.unmodifiableList(aemMultipleValues_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.class, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int RSSI_MULTIPLE_VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rssiMultipleValues_;
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     */
    public boolean hasRssiMultipleValues() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     */
    public com.google.protobuf.ByteString getRssiMultipleValues() {
      return rssiMultipleValues_;
    }

    public static final int RSSI_FIELD_NUMBER = 3;
    private int rssi_;
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasRssi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     */
    @java.lang.Deprecated public int getRssi() {
      return rssi_;
    }

    public static final int AEM_MULTIPLE_VALUES_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> aemMultipleValues_;
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getAemMultipleValuesList() {
      return aemMultipleValues_;
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    public int getAemMultipleValuesCount() {
      return aemMultipleValues_.size();
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    public com.google.protobuf.ByteString getAemMultipleValues(int index) {
      return aemMultipleValues_.get(index);
    }

    public static final int AEM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString aem_;
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasAem() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
      return aem_;
    }

    public static final int PREVIOUS_SCAN_TIMESTAMP_FIELD_NUMBER = 5;
    private int previousScanTimestamp_;
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     */
    public boolean hasPreviousScanTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     */
    public int getPreviousScanTimestamp() {
      return previousScanTimestamp_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 7;
    private double latitude_;
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 8;
    private double longitude_;
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int ACTIVITY_FIELD_NUMBER = 9;
    private int activity_;
    /**
     * <code>optional uint32 activity = 9;</code>
     */
    public boolean hasActivity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 activity = 9;</code>
     */
    public int getActivity() {
      return activity_;
    }

    public static final int LABEL_FIELD_NUMBER = 10;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 10;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string label = 10;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROB_FIELD_NUMBER = 11;
    private double prob_;
    /**
     * <code>optional double prob = 11;</code>
     */
    public boolean hasProb() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional double prob = 11;</code>
     */
    public double getProb() {
      return prob_;
    }

    public static final int VECTORS_FIELD_NUMBER = 12;
    private volatile java.lang.Object vectors_;
    /**
     * <code>optional string vectors = 12;</code>
     */
    public boolean hasVectors() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string vectors = 12;</code>
     */
    public java.lang.String getVectors() {
      java.lang.Object ref = vectors_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vectors_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vectors = 12;</code>
     */
    public com.google.protobuf.ByteString
        getVectorsBytes() {
      java.lang.Object ref = vectors_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vectors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, rssiMultipleValues_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rssi_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, aem_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, previousScanTimestamp_);
      }
      for (int i = 0; i < aemMultipleValues_.size(); i++) {
        output.writeBytes(6, aemMultipleValues_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(7, latitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(8, longitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, activity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, label_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(11, prob_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, vectors_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rssiMultipleValues_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rssi_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, aem_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, previousScanTimestamp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < aemMultipleValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(aemMultipleValues_.get(i));
        }
        size += dataSize;
        size += 1 * getAemMultipleValuesList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, latitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, longitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, activity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, label_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, prob_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, vectors_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord)) {
        return super.equals(obj);
      }
      com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord other = (com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasRssiMultipleValues() == other.hasRssiMultipleValues());
      if (hasRssiMultipleValues()) {
        result = result && getRssiMultipleValues()
            .equals(other.getRssiMultipleValues());
      }
      result = result && (hasRssi() == other.hasRssi());
      if (hasRssi()) {
        result = result && (getRssi()
            == other.getRssi());
      }
      result = result && getAemMultipleValuesList()
          .equals(other.getAemMultipleValuesList());
      result = result && (hasAem() == other.hasAem());
      if (hasAem()) {
        result = result && getAem()
            .equals(other.getAem());
      }
      result = result && (hasPreviousScanTimestamp() == other.hasPreviousScanTimestamp());
      if (hasPreviousScanTimestamp()) {
        result = result && (getPreviousScanTimestamp()
            == other.getPreviousScanTimestamp());
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && (hasActivity() == other.hasActivity());
      if (hasActivity()) {
        result = result && (getActivity()
            == other.getActivity());
      }
      result = result && (hasLabel() == other.hasLabel());
      if (hasLabel()) {
        result = result && getLabel()
            .equals(other.getLabel());
      }
      result = result && (hasProb() == other.hasProb());
      if (hasProb()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getProb())
            == java.lang.Double.doubleToLongBits(
                other.getProb()));
      }
      result = result && (hasVectors() == other.hasVectors());
      if (hasVectors()) {
        result = result && getVectors()
            .equals(other.getVectors());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      if (hasRssiMultipleValues()) {
        hash = (37 * hash) + RSSI_MULTIPLE_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getRssiMultipleValues().hashCode();
      }
      if (hasRssi()) {
        hash = (37 * hash) + RSSI_FIELD_NUMBER;
        hash = (53 * hash) + getRssi();
      }
      if (getAemMultipleValuesCount() > 0) {
        hash = (37 * hash) + AEM_MULTIPLE_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getAemMultipleValuesList().hashCode();
      }
      if (hasAem()) {
        hash = (37 * hash) + AEM_FIELD_NUMBER;
        hash = (53 * hash) + getAem().hashCode();
      }
      if (hasPreviousScanTimestamp()) {
        hash = (37 * hash) + PREVIOUS_SCAN_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getPreviousScanTimestamp();
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasActivity()) {
        hash = (37 * hash) + ACTIVITY_FIELD_NUMBER;
        hash = (53 * hash) + getActivity();
      }
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      if (hasProb()) {
        hash = (37 * hash) + PROB_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getProb()));
      }
      if (hasVectors()) {
        hash = (37 * hash) + VECTORS_FIELD_NUMBER;
        hash = (53 * hash) + getVectors().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ScanRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ScanRecord)
        com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.class, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
      }

      // Construct using com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        rssi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        aemMultipleValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        aem_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        previousScanTimestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        activity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        prob_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        vectors_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance();
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord build() {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord buildPartial() {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord result = new com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rssiMultipleValues_ = rssiMultipleValues_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rssi_ = rssi_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          aemMultipleValues_ = java.util.Collections.unmodifiableList(aemMultipleValues_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.aemMultipleValues_ = aemMultipleValues_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.aem_ = aem_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.previousScanTimestamp_ = previousScanTimestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.activity_ = activity_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.prob_ = prob_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.vectors_ = vectors_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord) {
          return mergeFrom((com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord other) {
        if (other == com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasRssiMultipleValues()) {
          setRssiMultipleValues(other.getRssiMultipleValues());
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        if (!other.aemMultipleValues_.isEmpty()) {
          if (aemMultipleValues_.isEmpty()) {
            aemMultipleValues_ = other.aemMultipleValues_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAemMultipleValuesIsMutable();
            aemMultipleValues_.addAll(other.aemMultipleValues_);
          }
          onChanged();
        }
        if (other.hasAem()) {
          setAem(other.getAem());
        }
        if (other.hasPreviousScanTimestamp()) {
          setPreviousScanTimestamp(other.getPreviousScanTimestamp());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasActivity()) {
          setActivity(other.getActivity());
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000200;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasProb()) {
          setProb(other.getProb());
        }
        if (other.hasVectors()) {
          bitField0_ |= 0x00000800;
          vectors_ = other.vectors_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>optional uint32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       */
      public boolean hasRssiMultipleValues() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       */
      public com.google.protobuf.ByteString getRssiMultipleValues() {
        return rssiMultipleValues_;
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       */
      public Builder setRssiMultipleValues(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rssiMultipleValues_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       */
      public Builder clearRssiMultipleValues() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rssiMultipleValues_ = getDefaultInstance().getRssiMultipleValues();
        onChanged();
        return this;
      }

      private int rssi_ ;
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       */
      @java.lang.Deprecated public boolean hasRssi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       */
      @java.lang.Deprecated public int getRssi() {
        return rssi_;
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setRssi(int value) {
        bitField0_ |= 0x00000004;
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rssi_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> aemMultipleValues_ = java.util.Collections.emptyList();
      private void ensureAemMultipleValuesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          aemMultipleValues_ = new java.util.ArrayList<com.google.protobuf.ByteString>(aemMultipleValues_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getAemMultipleValuesList() {
        return java.util.Collections.unmodifiableList(aemMultipleValues_);
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public int getAemMultipleValuesCount() {
        return aemMultipleValues_.size();
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public com.google.protobuf.ByteString getAemMultipleValues(int index) {
        return aemMultipleValues_.get(index);
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public Builder setAemMultipleValues(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAemMultipleValuesIsMutable();
        aemMultipleValues_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public Builder addAemMultipleValues(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAemMultipleValuesIsMutable();
        aemMultipleValues_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public Builder addAllAemMultipleValues(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureAemMultipleValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aemMultipleValues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       */
      public Builder clearAemMultipleValues() {
        aemMultipleValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString aem_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       */
      @java.lang.Deprecated public boolean hasAem() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
        return aem_;
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setAem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        aem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearAem() {
        bitField0_ = (bitField0_ & ~0x00000010);
        aem_ = getDefaultInstance().getAem();
        onChanged();
        return this;
      }

      private int previousScanTimestamp_ ;
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       */
      public boolean hasPreviousScanTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       */
      public int getPreviousScanTimestamp() {
        return previousScanTimestamp_;
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       */
      public Builder setPreviousScanTimestamp(int value) {
        bitField0_ |= 0x00000020;
        previousScanTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       */
      public Builder clearPreviousScanTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        previousScanTimestamp_ = 0;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000040;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000080;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000080);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private int activity_ ;
      /**
       * <code>optional uint32 activity = 9;</code>
       */
      public boolean hasActivity() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 activity = 9;</code>
       */
      public int getActivity() {
        return activity_;
      }
      /**
       * <code>optional uint32 activity = 9;</code>
       */
      public Builder setActivity(int value) {
        bitField0_ |= 0x00000100;
        activity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 activity = 9;</code>
       */
      public Builder clearActivity() {
        bitField0_ = (bitField0_ & ~0x00000100);
        activity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 10;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string label = 10;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            label_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 10;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 10;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000200);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 10;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        label_ = value;
        onChanged();
        return this;
      }

      private double prob_ ;
      /**
       * <code>optional double prob = 11;</code>
       */
      public boolean hasProb() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double prob = 11;</code>
       */
      public double getProb() {
        return prob_;
      }
      /**
       * <code>optional double prob = 11;</code>
       */
      public Builder setProb(double value) {
        bitField0_ |= 0x00000400;
        prob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double prob = 11;</code>
       */
      public Builder clearProb() {
        bitField0_ = (bitField0_ & ~0x00000400);
        prob_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object vectors_ = "";
      /**
       * <code>optional string vectors = 12;</code>
       */
      public boolean hasVectors() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string vectors = 12;</code>
       */
      public java.lang.String getVectors() {
        java.lang.Object ref = vectors_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vectors_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string vectors = 12;</code>
       */
      public com.google.protobuf.ByteString
          getVectorsBytes() {
        java.lang.Object ref = vectors_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vectors_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vectors = 12;</code>
       */
      public Builder setVectors(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        vectors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vectors = 12;</code>
       */
      public Builder clearVectors() {
        bitField0_ = (bitField0_ & ~0x00000800);
        vectors_ = getDefaultInstance().getVectors();
        onChanged();
        return this;
      }
      /**
       * <code>optional string vectors = 12;</code>
       */
      public Builder setVectorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        vectors_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ScanRecord)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ScanRecord)
    private static final com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord();
    }

    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScanRecord>
        PARSER = new com.google.protobuf.AbstractParser<ScanRecord>() {
      public ScanRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ScanRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScanRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanRecord> getParserForType() {
      return PARSER;
    }

    public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactRecordsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ContactRecords)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> 
        getRecordList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index);
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    int getRecordCount();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<? extends com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gmsreadout.ContactRecords}
   */
  public  static final class ContactRecords extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ContactRecords)
      ContactRecordsOrBuilder {
    // Use ContactRecords.newBuilder() to construct.
    private ContactRecords(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactRecords() {
      record_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactRecords(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                record_ = new java.util.ArrayList<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              record_.add(
                  input.readMessage(com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = java.util.Collections.unmodifiableList(record_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.class, com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
    }

    public static final int RECORD_FIELD_NUMBER = 1;
    private java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> record_;
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public java.util.List<? extends com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public int getRecordCount() {
      return record_.size();
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
      return record_.get(index);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < record_.size(); i++) {
        output.writeMessage(1, record_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < record_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, record_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords)) {
        return super.equals(obj);
      }
      com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords other = (com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords) obj;

      boolean result = true;
      result = result && getRecordList()
          .equals(other.getRecordList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecordCount() > 0) {
        hash = (37 * hash) + RECORD_FIELD_NUMBER;
        hash = (53 * hash) + getRecordList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ContactRecords}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ContactRecords)
        com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecordsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.class, com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
      }

      // Construct using com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
        return com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance();
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords build() {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords buildPartial() {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords result = new com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords(this);
        int from_bitField0_ = bitField0_;
        if (recordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            record_ = java.util.Collections.unmodifiableList(record_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.record_ = record_;
        } else {
          result.record_ = recordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords) {
          return mergeFrom((com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords other) {
        if (other == com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance()) return this;
        if (recordBuilder_ == null) {
          if (!other.record_.isEmpty()) {
            if (record_.isEmpty()) {
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordIsMutable();
              record_.addAll(other.record_);
            }
            onChanged();
          }
        } else {
          if (!other.record_.isEmpty()) {
            if (recordBuilder_.isEmpty()) {
              recordBuilder_.dispose();
              recordBuilder_ = null;
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordFieldBuilder() : null;
            } else {
              recordBuilder_.addAllMessages(other.record_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> record_ =
        java.util.Collections.emptyList();
      private void ensureRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = new java.util.ArrayList<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord>(record_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> recordBuilder_;

      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
        if (recordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(record_);
        } else {
          return recordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public int getRecordCount() {
        if (recordBuilder_ == null) {
          return record_.size();
        } else {
          return recordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);
        } else {
          return recordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.set(index, value);
          onChanged();
        } else {
          recordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(value);
          onChanged();
        } else {
          recordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(index, value);
          onChanged();
        } else {
          recordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addAllRecord(
          java.lang.Iterable<? extends com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord> values) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, record_);
          onChanged();
        } else {
          recordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder clearRecord() {
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder removeRecord(int index) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.remove(index);
          onChanged();
        } else {
          recordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder getRecordBuilder(
          int index) {
        return getRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
          int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);  } else {
          return recordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<? extends com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
           getRecordOrBuilderList() {
        if (recordBuilder_ != null) {
          return recordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(record_);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder() {
        return getRecordFieldBuilder().addBuilder(
            com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder(
          int index) {
        return getRecordFieldBuilder().addBuilder(
            index, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder> 
           getRecordBuilderList() {
        return getRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
          getRecordFieldBuilder() {
        if (recordBuilder_ == null) {
          recordBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, com.example.database_test.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder>(
                  record_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          record_ = null;
        }
        return recordBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ContactRecords)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ContactRecords)
    private static final com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords();
    }

    public static com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContactRecords>
        PARSER = new com.google.protobuf.AbstractParser<ContactRecords>() {
      public ContactRecords parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContactRecords(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactRecords> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactRecords> getParserForType() {
      return PARSER;
    }

    public com.example.database_test.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ScanRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ScanRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ContactRecords_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ContactRecords_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ContactRecords.proto\022\ngmsreadout\"\203\002\n\nS" +
      "canRecord\022\021\n\ttimestamp\030\001 \001(\r\022\034\n\024rssi_mul" +
      "tiple_values\030\002 \001(\014\022\020\n\004rssi\030\003 \001(\005B\002\030\001\022\033\n\023" +
      "aem_multiple_values\030\006 \003(\014\022\017\n\003aem\030\004 \001(\014B\002" +
      "\030\001\022\037\n\027previous_scan_timestamp\030\005 \001(\r\022\020\n\010l" +
      "atitude\030\007 \001(\001\022\021\n\tlongitude\030\010 \001(\001\022\020\n\010acti" +
      "vity\030\t \001(\r\022\r\n\005label\030\n \001(\t\022\014\n\004prob\030\013 \001(\001\022" +
      "\017\n\007vectors\030\014 \001(\t\"8\n\016ContactRecords\022&\n\006re" +
      "cord\030\001 \003(\0132\026.gmsreadout.ScanRecordB<\n$co" +
      "m.example.database_test.gmsreadoutB\024Cont",
      "actRecordsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gmsreadout_ScanRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gmsreadout_ScanRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ScanRecord_descriptor,
        new java.lang.String[] { "Timestamp", "RssiMultipleValues", "Rssi", "AemMultipleValues", "Aem", "PreviousScanTimestamp", "Latitude", "Longitude", "Activity", "Label", "Prob", "Vectors", });
    internal_static_gmsreadout_ContactRecords_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gmsreadout_ContactRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ContactRecords_descriptor,
        new java.lang.String[] { "Record", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
